Ember.I18n.translations = {
    'title': 'Mötesplatsen - Hitta kärleken på nätet',

	'user_entry.geo.location': '{{age}} år från {{location}}',
	'user_entry.seeks.gender.man': 'man',
	'user_entry.seeks.gender.woman': 'kvinna',
	'user_entry.seeks.short': 'Söker {{seekssex}} {{seeksagefrom}}-{{seeksageto}} år',
	'user_entry.age': '{{age}} år',
	'user_entry.new': 'NYTT',
	'user_entry.menu.favorite': 'Favorit',
	'user_entry.menu.hide': 'Dölj',
	'user_entry.menu.show': 'Visa',
	'visitors.filter.show_only_pictures': 'Visa endast de med foto',
	'visitors.filter.photo_mode': 'Visa fotovy',
	'visitors.title': 'Besökare',
	'visitors.total_visits': 'Totalt antal besök: {{count}}',
	'visitors.menu.visitors': 'Mina Besök',
	'visitors.menu.visits': 'De jag besökt',
	'visited.title': 'Besökta',
	'visitors.loading': 'Laddar ...',
	'visitors.load_more': 'Ladda mer',
	'visited.total_visits': 'Totalt antal besök: {{count}}',
	'visited.menu.visitors': 'Mina Besök',
	'visited.menu.visits': 'De jag besökt',
	'navigation.home': 'Startsidan',
	'navigation.my_messages': 'Meddelanden',
	'navigation.my_visitors': 'Besökare',
	'navigation.my_contacts': 'Favoriter',
	'navigation.category.find_singles': 'Hitta singlar',
	'navigation.search_singles': 'Sök singlar',
	'navigation.search_matching': 'Matchning',
	'navigation.online_list': 'Singlar online',
	'navigation.new_singles': 'Nya singlar',
	'navigation.category.socialize': 'Umgås',
	'navigation.photos': 'Foton',
	'navigation.go_on_date': 'Gå på dejt',
	'navigation.forum': 'Prata',
	'navigation.quiz': 'Quiz',
	'navigation.category.presentation': 'Presentera dig',
	'navigation.my_profile': 'Profil',
	'navigation.picture_personal.header': 'Profilfoto',
	'navigation.picture_personal.text': 'Ladda upp ett profilfoto så ökar dina chanser!',
	'navigation.my_photos': 'Ändra foton',
	'navigation.about_me': 'Ändra fakta',
	'navigation.category.account': 'Inställningar',
	//VIP
	'navigation.vipstatus.become_vip_header': 'Passa på!',
	'navigation.vipstatus.become_vip': 'Bli VIP-medlem idag och kom i kontakt med tusentals singlar!',
	'navigation.vipstatus.vip_soon_over': 'VIP snart slut',
	'navigation.vipstatus.vip_days_left.one': '1 VIP-dag kvar',
	'navigation.vipstatus.vip_days_left.other': '{{vipdays}} VIP-dagar kvar',
	'navigation.vipstatus.is_vip': 'Du är VIP',

	'navigation.help': 'Hjälp',
	'navigation.settings': 'Inställningar',
	'navigation.logout': 'Logga ut',
	'megaphone.title': 'Megafon',
	'megaphone.write': 'Vill du synas här?',
	'megaphone.no_megaphone.header': 'Öka dina chanser',
	'megaphone.no_megaphone.text': 'Visa att du finns. Skriv i megafonen så får du fler besök till din profil!',
	'onlinelist.title': 'Online {{count}}',
	'onlinelist.more_to_see': 'Se fler',
	'text_ad.title': 'Tips'
}