function FastClick(b){var d,c=this;this.trackingClick=!1;this.trackingClickStart=0;this.targetElement=null;this.lastTouchIdentifier=this.touchStartY=this.touchStartX=0;this.touchBoundary=10;this.layer=b;if(!b||!b.nodeType)throw new TypeError("Layer must be a document node");this.onClick=function(){return FastClick.prototype.onClick.apply(c,arguments)};this.onMouse=function(){return FastClick.prototype.onMouse.apply(c,arguments)};this.onTouchStart=function(){return FastClick.prototype.onTouchStart.apply(c,
arguments)};this.onTouchMove=function(){return FastClick.prototype.onTouchMove.apply(c,arguments)};this.onTouchEnd=function(){return FastClick.prototype.onTouchEnd.apply(c,arguments)};this.onTouchCancel=function(){return FastClick.prototype.onTouchCancel.apply(c,arguments)};FastClick.notNeeded(b)||(this.deviceIsAndroid&&(b.addEventListener("mouseover",this.onMouse,!0),b.addEventListener("mousedown",this.onMouse,!0),b.addEventListener("mouseup",this.onMouse,!0)),b.addEventListener("click",this.onClick,
!0),b.addEventListener("touchstart",this.onTouchStart,!1),b.addEventListener("touchmove",this.onTouchMove,!1),b.addEventListener("touchend",this.onTouchEnd,!1),b.addEventListener("touchcancel",this.onTouchCancel,!1),Event.prototype.stopImmediatePropagation||(b.removeEventListener=function(c,d,m){var h=Node.prototype.removeEventListener;"click"===c?h.call(b,c,d.hijacked||d,m):h.call(b,c,d,m)},b.addEventListener=function(c,d,m){var h=Node.prototype.addEventListener;"click"===c?h.call(b,c,d.hijacked||
(d.hijacked=function(c){c.propagationStopped||d(c)}),m):h.call(b,c,d,m)}),"function"===typeof b.onclick&&(d=b.onclick,b.addEventListener("click",function(c){d(c)},!1),b.onclick=null))}FastClick.prototype.deviceIsAndroid=0<navigator.userAgent.indexOf("Android");FastClick.prototype.deviceIsIOS=/iP(ad|hone|od)/.test(navigator.userAgent);FastClick.prototype.deviceIsIOS4=FastClick.prototype.deviceIsIOS&&/OS 4_\d(_\d)?/.test(navigator.userAgent);
FastClick.prototype.deviceIsIOSWithBadTarget=FastClick.prototype.deviceIsIOS&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);FastClick.prototype.needsClick=function(b){switch(b.nodeName.toLowerCase()){case "button":case "select":case "textarea":if(b.disabled)return!0;break;case "input":if(this.deviceIsIOS&&"file"===b.type||b.disabled)return!0;break;case "label":case "video":return!0}return/\bneedsclick\b/.test(b.className)};
FastClick.prototype.needsFocus=function(b){switch(b.nodeName.toLowerCase()){case "textarea":case "select":return!0;case "input":switch(b.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return!1}return!b.disabled&&!b.readOnly;default:return/\bneedsfocus\b/.test(b.className)}};
FastClick.prototype.sendClick=function(b,d){var c,g;document.activeElement&&document.activeElement!==b&&document.activeElement.blur();g=d.changedTouches[0];c=document.createEvent("MouseEvents");c.initMouseEvent("click",!0,!0,window,1,g.screenX,g.screenY,g.clientX,g.clientY,!1,!1,!1,!1,0,null);c.forwardedTouchEvent=!0;b.dispatchEvent(c)};FastClick.prototype.focus=function(b){var d;this.deviceIsIOS&&b.setSelectionRange?(d=b.value.length,b.setSelectionRange(d,d)):b.focus()};
FastClick.prototype.updateScrollParent=function(b){var d,c;d=b.fastClickScrollParent;if(!d||!d.contains(b)){c=b;do{if(c.scrollHeight>c.offsetHeight){d=c;b.fastClickScrollParent=c;break}c=c.parentElement}while(c)}d&&(d.fastClickLastScrollTop=d.scrollTop)};FastClick.prototype.getTargetElementFromEventTarget=function(b){return b.nodeType===Node.TEXT_NODE?b.parentNode:b};
FastClick.prototype.onTouchStart=function(b){var d,c,g;if(1<b.targetTouches.length)return!0;d=this.getTargetElementFromEventTarget(b.target);c=b.targetTouches[0];if(this.deviceIsIOS){g=window.getSelection();if(g.rangeCount&&!g.isCollapsed)return!0;if(!this.deviceIsIOS4){if(c.identifier===this.lastTouchIdentifier)return b.preventDefault(),!1;this.lastTouchIdentifier=c.identifier;this.updateScrollParent(d)}}this.trackingClick=!0;this.trackingClickStart=b.timeStamp;this.targetElement=d;this.touchStartX=
c.pageX;this.touchStartY=c.pageY;200>b.timeStamp-this.lastClickTime&&b.preventDefault();return!0};FastClick.prototype.touchHasMoved=function(b){b=b.changedTouches[0];var d=this.touchBoundary;return Math.abs(b.pageX-this.touchStartX)>d||Math.abs(b.pageY-this.touchStartY)>d?!0:!1};FastClick.prototype.onTouchMove=function(b){if(!this.trackingClick)return!0;if(this.targetElement!==this.getTargetElementFromEventTarget(b.target)||this.touchHasMoved(b))this.trackingClick=!1,this.targetElement=null;return!0};
FastClick.prototype.findControl=function(b){return void 0!==b.control?b.control:b.htmlFor?document.getElementById(b.htmlFor):b.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};
FastClick.prototype.onTouchEnd=function(b){var d,c,g=this.targetElement;if(!this.trackingClick)return!0;if(200>b.timeStamp-this.lastClickTime)return this.cancelNextClick=!0;this.lastClickTime=b.timeStamp;d=this.trackingClickStart;this.trackingClick=!1;this.trackingClickStart=0;this.deviceIsIOSWithBadTarget&&(c=b.changedTouches[0],g=document.elementFromPoint(c.pageX-window.pageXOffset,c.pageY-window.pageYOffset)||g,g.fastClickScrollParent=this.targetElement.fastClickScrollParent);c=g.tagName.toLowerCase();
if("label"===c){if(d=this.findControl(g)){this.focus(g);if(this.deviceIsAndroid)return!1;g=d}}else if(this.needsFocus(g)){if(100<b.timeStamp-d||this.deviceIsIOS&&window.top!==window&&"input"===c)return this.targetElement=null,!1;this.focus(g);this.deviceIsIOS4&&"select"===c||(this.targetElement=null,b.preventDefault());return!1}if(this.deviceIsIOS&&!this.deviceIsIOS4&&(d=g.fastClickScrollParent)&&d.fastClickLastScrollTop!==d.scrollTop)return!0;this.needsClick(g)||(b.preventDefault(),this.sendClick(g,
b));return!1};FastClick.prototype.onTouchCancel=function(){this.trackingClick=!1;this.targetElement=null};FastClick.prototype.onMouse=function(b){return this.targetElement&&!b.forwardedTouchEvent&&b.cancelable?!this.needsClick(this.targetElement)||this.cancelNextClick?(b.stopImmediatePropagation?b.stopImmediatePropagation():b.propagationStopped=!0,b.stopPropagation(),b.preventDefault(),!1):!0:!0};
FastClick.prototype.onClick=function(b){if(this.trackingClick)return this.targetElement=null,this.trackingClick=!1,!0;if("submit"===b.target.type&&0===b.detail)return!0;(b=this.onMouse(b))||(this.targetElement=null);return b};
FastClick.prototype.destroy=function(){var b=this.layer;this.deviceIsAndroid&&(b.removeEventListener("mouseover",this.onMouse,!0),b.removeEventListener("mousedown",this.onMouse,!0),b.removeEventListener("mouseup",this.onMouse,!0));b.removeEventListener("click",this.onClick,!0);b.removeEventListener("touchstart",this.onTouchStart,!1);b.removeEventListener("touchmove",this.onTouchMove,!1);b.removeEventListener("touchend",this.onTouchEnd,!1);b.removeEventListener("touchcancel",this.onTouchCancel,!1)};
FastClick.notNeeded=function(b){var d;if("undefined"===typeof window.ontouchstart)return!0;if(/Chrome\/[0-9]+/.test(navigator.userAgent))if(FastClick.prototype.deviceIsAndroid){if((d=document.querySelector("meta[name=viewport]"))&&-1!==d.content.indexOf("user-scalable=no"))return!0}else return!0;return"none"===b.style.msTouchAction?!0:!1};FastClick.attach=function(b){return new FastClick(b)};
"undefined"!==typeof define&&define.amd?define(function(){return FastClick}):"undefined"!==typeof module&&module.exports?(module.exports=FastClick.attach,module.exports.FastClick=FastClick):window.FastClick=FastClick;var IScroll=function(b,d,c){function g(a,e){this.wrapper="string"==typeof a?d.querySelector(a):a;this.scroller=this.wrapper.children[0];this.scrollerStyle=this.scroller.style;this.options={resizeIndicator:!0,mouseWheelSpeed:20,snapThreshold:0.334,startX:0,startY:0,scrollY:!0,directionLockThreshold:5,momentum:!0,bounce:!0,bounceTime:600,bounceEasing:"",preventDefault:!0,preventDefaultException:{tagName:/^(INPUT|TEXTAREA|BUTTON|SELECT)$/},HWCompositing:!0,useTransition:!0,useTransform:!0,deceleration:6E-4,
speedRatio:1,maxMomentumDistance:0,maxMomentumDuration:0};for(var c in e)this.options[c]=e[c];this.translateZ=this.options.HWCompositing&&f.hasPerspective?" translateZ(0)":"";this.options.useTransition=f.hasTransition&&this.options.useTransition;this.options.useTransform=f.hasTransform&&this.options.useTransform;this.options.eventPassthrough=!0===this.options.eventPassthrough?"vertical":this.options.eventPassthrough;this.options.preventDefault=!this.options.eventPassthrough&&this.options.preventDefault;
this.options.scrollY="vertical"==this.options.eventPassthrough?!1:this.options.scrollY;this.options.scrollX="horizontal"==this.options.eventPassthrough?!1:this.options.scrollX;this.options.freeScroll=this.options.freeScroll&&!this.options.eventPassthrough;this.options.directionLockThreshold=this.options.eventPassthrough?0:this.options.directionLockThreshold;this.options.bounceEasing="string"==typeof this.options.bounceEasing?f.ease[this.options.bounceEasing]||f.ease.circular:this.options.bounceEasing;
this.options.resizePolling=void 0===this.options.resizePolling?60:this.options.resizePolling;!0===this.options.tap&&(this.options.tap="tap");this.options.invertWheelDirection=this.options.invertWheelDirection?-1:1;this.directionY=this.directionX=this.y=this.x=0;this._events={};this._init();this.refresh();this.scrollTo(this.options.startX,this.options.startY);this.enable()}function l(a,e,c){var b=d.createElement("div"),f=d.createElement("div");!0===c&&(b.style.cssText="position:absolute;z-index:9999;opacity:0;-webkit-transition: opacity 0.3s;-webkit-backface-visibility: hidden;",
f.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:absolute;background:rgba(0,0,0,0.3);border:1px solid rgba(255,255,255,0.5);border-radius:"+T.p(3)+"px");f.className="iScrollIndicator";"h"==a?(!0===c&&(b.style.cssText+=";height:7px;left:2px;right:2px;bottom:0",f.style.height="100%"),b.className="iScrollHorizontalScrollbar"):(!0===c&&(b.style.cssText+=";width:"+T.p(5)+"px;bottom:"+T.p(2)+"px;top:"+T.p(2)+"px;right:"+T.p(3)+"px",f.style.width="100%"),
b.className="iScrollVerticalScrollbar");e||(b.style.pointerEvents="none");b.appendChild(f);return b}function m(a,e){this.wrapper="string"==typeof e.el?d.querySelector(e.el):e.el;this.indicator=this.wrapper.children[0];this.indicatorStyle=this.indicator.style;this.scroller=a;this.options={listenX:!0,listenY:!0,interactive:!1,resize:!0,defaultScrollbars:!1,speedRatioX:0,speedRatioY:0};for(var c in e)this.options[c]=e[c];this.sizeRatioY=this.sizeRatioX=1;this.maxPosY=this.maxPosX=0;this.options.interactive&&
(this.options.disableTouch||(f.addEvent(this.indicator,"touchstart",this),f.addEvent(b,"touchend",this)),this.options.disablePointer||(f.addEvent(this.indicator,"MSPointerDown",this),f.addEvent(b,"MSPointerUp",this)),this.options.disableMouse||(f.addEvent(this.indicator,"mousedown",this),f.addEvent(b,"mouseup",this)))}var h=b.requestAnimationFrame||b.webkitRequestAnimationFrame||b.mozRequestAnimationFrame||b.oRequestAnimationFrame||b.msRequestAnimationFrame||function(a){b.setTimeout(a,1E3/60)},f=
function(){function a(a){return!1===v?!1:""===v?a:v+a.charAt(0).toUpperCase()+a.substr(1)}var e={},u=d.createElement("div").style,v=function(){for(var a=["t","webkitT","MozT","msT","OT"],e,c=0,b=a.length;c<b;c++)if(e=a[c]+"ransform",e in u)return a[c].substr(0,a[c].length-1);return!1}();e.getTime=Date.now||function(){return(new Date).getTime()};e.extend=function(a,e){for(var c in e)a[c]=e[c]};e.addEvent=function(a,e,c,b){a.addEventListener(e,c,!!b)};e.removeEvent=function(a,e,c,b){a.removeEventListener(e,
c,!!b)};e.momentum=function(a,e,b,d,u,v){var f=a-e;b=c.abs(f)/b*v.speedRatio;var p,g=v.deceleration;p=a+b*b/(2*g)*(0>f?-1:1);f=b/g;v.maxMomentumDistance&&c.abs(a-p)>v.maxMomentumDistance&&(p=a+(0>e-a?1:-1)*v.maxMomentumDistance,f=v.maxMomentumDuration/b);p<d?(p=u?d-u/2.5*(b/16):d,f=c.abs(p-a),f/=b):0<p&&(p=u?u/2.5*(b/16):0,f=c.abs(a)+p,f/=b);return{destination:c.round(p),duration:f}};var f=a("transform");e.extend(e,{hasTransform:!1!==f,hasPerspective:a("perspective")in u,hasTouch:"ontouchstart"in
b,hasPointer:navigator.msPointerEnabled,hasTransition:a("transition")in u});e.isAndroidBrowser=/Android/.test(b.navigator.appVersion)&&/Version\/\d/.test(b.navigator.appVersion);e.extend(e.style={},{transform:f,transitionTimingFunction:a("transitionTimingFunction"),transitionDuration:a("transitionDuration"),transformOrigin:a("transformOrigin")});e.hasClass=function(a,e){return RegExp("(^|\\s)"+e+"(\\s|$)").test(a.className)};e.addClass=function(a,c){if(!e.hasClass(a,c)){var b=a.className.split(" ");
b.push(c);a.className=b.join(" ")}};e.removeClass=function(a,c){e.hasClass(a,c)&&(a.className=a.className.replace(RegExp("(^|\\s)"+c+"(\\s|$)","g")," "))};e.offset=function(a){for(var e=-a.offsetLeft,c=-a.offsetTop;a=a.offsetParent;)e-=a.offsetLeft,c-=a.offsetTop;return{left:e,top:c}};e.preventDefaultException=function(a,e){for(var c in e)if(e[c].test(a[c]))return!0;return!1};e.extend(e.eventType={},{touchstart:1,touchmove:1,touchend:1,mousedown:2,mousemove:2,mouseup:2,MSPointerDown:3,MSPointerMove:3,
MSPointerUp:3});e.extend(e.ease={},{quadratic:{style:"cubic-bezier(0.25, 0.46, 0.45, 0.94)",fn:function(a){return a*(2-a)}},circular:{style:"cubic-bezier(0.1, 0.57, 0.1, 1)",fn:function(a){return c.sqrt(1- --a*a)}},back:{style:"cubic-bezier(0.175, 0.885, 0.32, 1.275)",fn:function(a){return(a-=1)*a*(5*a+4)+1}},quadratic2:{style:"",fn:function(a){return a*(2-a)}},bounce:{style:"",fn:function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:
7.5625*(a-=2.625/2.75)*a+0.984375}},elastic:{style:"",fn:function(a){return 0===a?0:1==a?1:0.4*c.pow(2,-10*a)*c.sin((a-0.055)*2*c.PI/0.22)+1}}});e.tap=function(a,e){var c=d.createEvent("Event");c.initEvent(e,!0,!0);c.pageX=a.pageX;c.pageY=a.pageY;a.target.dispatchEvent(c)};e.click=function(a){var e=a.target,c;"SELECT"!=e.tagName&&("INPUT"!=e.tagName&&"TEXTAREA"!=e.tagName)&&(c=d.createEvent("MouseEvents"),c.initMouseEvent("click",!0,!0,a.view,1,e.screenX,e.screenY,e.clientX,e.clientY,a.ctrlKey,a.altKey,
a.shiftKey,a.metaKey,0,null),c._constructed=!0,e.dispatchEvent(c))};return e}();g.prototype={version:"5.0.6",_init:function(){this._initEvents();(this.options.scrollbars||this.options.indicators)&&this._initIndicators();this.options.mouseWheel&&this._initWheel();this.options.snap&&this._initSnap();this.options.keyBindings&&this._initKeys()},destroy:function(){this._initEvents(!0);this._execEvent("destroy")},_transitionEnd:function(a){a.target==this.scroller&&(this._transitionTime(0),this.resetPosition(this.options.bounceTime)||
this._execEvent("scrollEnd"))},_start:function(a){if(!(1!=f.eventType[a.type]&&0!==a.button)&&this.enabled&&!(this.initiated&&f.eventType[a.type]!==this.initiated)){this.options.preventDefault&&(!f.isAndroidBrowser&&!f.preventDefaultException(a.target,this.options.preventDefaultException))&&a.preventDefault();var e=a.touches?a.touches[0]:a;this.initiated=f.eventType[a.type];this.moved=!1;this.directionLocked=this.directionY=this.directionX=this.distY=this.distX=0;this._transitionTime();this.isAnimating=
!1;this.startTime=f.getTime();this.options.useTransition&&this.isInTransition&&(a=this.getComputedPosition(),this._translate(c.round(a.x),c.round(a.y)),this._execEvent("scrollEnd"),this.isInTransition=!1);this.startX=this.x;this.startY=this.y;this.absStartX=this.x;this.absStartY=this.y;this.pointX=e.pageX;this.pointY=e.pageY;this.options.hideScrollbarsOnMove&&(this.indicators[0].wrapper.style.opacity=1);this._execEvent("beforeScrollStart")}},_move:function(a){if(this.enabled&&f.eventType[a.type]===
this.initiated){this.options.preventDefault&&a.preventDefault();var e=a.touches?a.touches[0]:a,b=e.pageX-this.pointX,d=e.pageY-this.pointY,p=f.getTime(),g;this.pointX=e.pageX;this.pointY=e.pageY;this.distX+=b;this.distY+=d;e=c.abs(this.distX);g=c.abs(this.distY);if(!(300<p-this.endTime&&10>e&&10>g)){!this.directionLocked&&!this.options.freeScroll&&(this.directionLocked=e>g+this.options.directionLockThreshold?"h":g>=e+this.options.directionLockThreshold?"v":"n");if("h"==this.directionLocked){if("vertical"==
this.options.eventPassthrough)a.preventDefault();else if("horizontal"==this.options.eventPassthrough){this.initiated=!1;return}d=0}else if("v"==this.directionLocked){if("horizontal"==this.options.eventPassthrough)a.preventDefault();else if("vertical"==this.options.eventPassthrough){this.initiated=!1;return}b=0}b=this.hasHorizontalScroll?b:0;d=this.hasVerticalScroll?d:0;a=this.x+b;e=this.y+d;if(0<a||a<this.maxScrollX)a=this.options.bounce?this.x+b/3:0<a?0:this.maxScrollX;if(0<e||e<this.maxScrollY)e=
this.options.bounce?this.y+d/3:0<e?0:this.maxScrollY;this.directionX=0<b?-1:0>b?1:0;this.directionY=0<d?-1:0>d?1:0;this.moved||this._execEvent("scrollStart");this.moved=!0;this._translate(a,e);300<p-this.startTime&&(this.startTime=p,this.startX=this.x,this.startY=this.y)}}},_end:function(a){if(this.enabled&&f.eventType[a.type]===this.initiated){this.options.preventDefault&&!f.preventDefaultException(a.target,this.options.preventDefaultException)&&a.preventDefault();this._execEvent("touchEnd");var e,
b;b=f.getTime()-this.startTime;var d=c.round(this.x),p=c.round(this.y),g=c.abs(d-this.startX),n=c.abs(p-this.startY);e=0;var h="";this.scrollTo(d,p);this.initiated=this.isInTransition=0;this.endTime=f.getTime();if(this.options.hideScrollbarsOnMove){var w=this;setTimeout(function(){w.indicators[0].wrapper.style.opacity=0},700)}if(!this.resetPosition(this.options.bounceTime))if(this.moved)if(this._events.flick&&200>b&&100>g&&100>n)this._execEvent("flick");else if(this.options.momentum&&300>b&&(e=this.hasHorizontalScroll?
f.momentum(this.x,this.startX,b,this.maxScrollX,this.options.bounce?this.wrapperWidth:0,this.options):{destination:d,duration:0},b=this.hasVerticalScroll?f.momentum(this.y,this.startY,b,this.maxScrollY,this.options.bounce?this.wrapperHeight:0,this.options):{destination:p,duration:0},d=e.destination,p=b.destination,e=c.max(e.duration,b.duration),this.isInTransition=1),this.options.snap&&(this.currentPage=h=this._nearestSnap(d,p),e=this.options.snapSpeed||c.max(c.max(c.min(c.abs(d-h.x),1E3),c.min(c.abs(p-
h.y),1E3)),300),d=h.x,p=h.y,this.directionY=this.directionX=0,h=this.options.bounceEasing),d!=this.x||p!=this.y){if(0<d||d<this.maxScrollX||0<p||p<this.maxScrollY)h=f.ease.quadratic;this.scrollTo(d,p,e,h)}else this._execEvent("scrollEnd");else this.options.tap&&f.tap(a,this.options.tap),this.options.click&&f.click(a)}},_resize:function(){var a=this;clearTimeout(this.resizeTimeout);this.resizeTimeout=setTimeout(function(){a.refresh()},this.options.resizePolling)},resetPosition:function(a){var e=this.x,
c=this.y;!this.hasHorizontalScroll||0<this.x?e=0:this.x<this.maxScrollX&&(e=this.maxScrollX);!this.hasVerticalScroll||0<this.y?c=0:this.y<this.maxScrollY&&(c=this.maxScrollY);if(e==this.x&&c==this.y)return!1;this.scrollTo(e,c,a||0,this.options.bounceEasing);return!0},disable:function(){this.enabled=!1},enable:function(){this.enabled=!0},refresh:function(){this.wrapperWidth=this.wrapper.clientWidth;this.wrapperHeight=this.wrapper.clientHeight;this.scrollerWidth=this.scroller.offsetWidth;this.scrollerHeight=
this.scroller.offsetHeight;this.maxScrollX=this.wrapperWidth-this.scrollerWidth;this.maxScrollY=this.wrapperHeight-this.scrollerHeight;this.hasHorizontalScroll=this.options.scrollX&&0>this.maxScrollX;this.hasVerticalScroll=this.options.scrollY&&0>this.maxScrollY;this.hasHorizontalScroll||(this.maxScrollX=0,this.scrollerWidth=this.wrapperWidth);this.hasVerticalScroll||(this.maxScrollY=0,this.scrollerHeight=this.wrapperHeight);this.directionY=this.directionX=this.endTime=0;this.wrapperOffset=f.offset(this.wrapper);
this._execEvent("refresh");this.resetPosition()},on:function(a,e){this._events[a]||(this._events[a]=[]);this._events[a].push(e)},_execEvent:function(a){if(this._events[a]){var e=0,c=this._events[a].length;if(c)for(;e<c;e++)this._events[a][e].call(this)}},scrollBy:function(a,e,c,b){a=this.x+a;e=this.y+e;this.scrollTo(a,e,c||0,b)},scrollTo:function(a,e,c,b){b=b||f.ease.circular;!c||this.options.useTransition&&b.style?(this._transitionTimingFunction(b.style),this._transitionTime(c),this._translate(a,
e)):this._animate(a,e,c,b.fn)},scrollToElement:function(a,e,b,d,p){if(a=a.nodeType?a:this.scroller.querySelector(a)){var g=f.offset(a);g.left-=this.wrapperOffset.left;g.top-=this.wrapperOffset.top;!0===b&&(b=c.round(a.offsetWidth/2-this.wrapper.offsetWidth/2));!0===d&&(d=c.round(a.offsetHeight/2-this.wrapper.offsetHeight/2));g.left-=b||0;g.top-=d||0;g.left=0<g.left?0:g.left<this.maxScrollX?this.maxScrollX:g.left;g.top=0<g.top?0:g.top<this.maxScrollY?this.maxScrollY:g.top;e=void 0===e||null===e||"auto"===
e?c.max(c.abs(this.x-g.left),c.abs(this.y-g.top)):e;this.scrollTo(g.left,g.top,e,p)}},_transitionTime:function(a){a=a||0;this.scrollerStyle[f.style.transitionDuration]=a+"ms";if(this.indicators)for(var e=this.indicators.length;e--;)this.indicators[e].transitionTime(a)},_transitionTimingFunction:function(a){this.scrollerStyle[f.style.transitionTimingFunction]=a;if(this.indicators)for(var e=this.indicators.length;e--;)this.indicators[e].transitionTimingFunction(a)},_translate:function(a,e){this.options.useTransform?
this.scrollerStyle[f.style.transform]="translate("+a+"px,"+e+"px)"+this.translateZ:(a=c.round(a),e=c.round(e),this.scrollerStyle.left=a+"px",this.scrollerStyle.top=e+"px");this.x=a;this.y=e;this._execEvent("translate");if(this.indicators)for(var b=this.indicators.length;b--;)this.indicators[b].updatePosition()},_initEvents:function(a){a=a?f.removeEvent:f.addEvent;var e=this.options.bindToWrapper?this.wrapper:b;a(b,"orientationchange",this);a(b,"resize",this);this.options.click&&a(this.wrapper,"click",
this,!0);this.options.disableMouse||(a(this.wrapper,"mousedown",this),a(e,"mousemove",this),a(e,"mousecancel",this),a(e,"mouseup",this));f.hasPointer&&!this.options.disablePointer&&(a(this.wrapper,"MSPointerDown",this),a(e,"MSPointerMove",this),a(e,"MSPointerCancel",this),a(e,"MSPointerUp",this));f.hasTouch&&!this.options.disableTouch&&(a(this.wrapper,"touchstart",this),a(e,"touchmove",this),a(e,"touchcancel",this),a(e,"touchend",this));a(this.scroller,"transitionend",this);a(this.scroller,"webkitTransitionEnd",
this);a(this.scroller,"oTransitionEnd",this);a(this.scroller,"MSTransitionEnd",this)},getComputedPosition:function(){var a=b.getComputedStyle(this.scroller,null),e;this.options.useTransform?(a=a[f.style.transform].split(")")[0].split(", "),e=+(a[12]||a[4]),a=+(a[13]||a[5])):(e=+a.left.replace(/[^-\d]/g,""),a=+a.top.replace(/[^-\d]/g,""));return{x:e,y:a}},_initIndicators:function(){var a=this.options.interactiveScrollbars,e="string"!=typeof this.options.scrollbars,c=[],b;this.indicators=[];this.options.scrollbars&&
(this.options.scrollY&&(b={el:l("v",a,this.options.scrollbars),interactive:a,defaultScrollbars:!0,customStyle:e,resize:this.options.resizeIndicator,listenX:!1},this.wrapper.appendChild(b.el),c.push(b)),this.options.scrollX&&(b={el:l("h",a,this.options.scrollbars),interactive:a,defaultScrollbars:!0,customStyle:e,resize:this.options.resizeIndicator,listenY:!1},this.wrapper.appendChild(b.el),c.push(b)));this.options.indicators&&(c=c.concat(this.options.indicators));for(a=c.length;a--;)this.indicators[a]=
new m(this,c[a]);this.on("refresh",function(){if(this.indicators)for(var a=this.indicators.length;a--;)this.indicators[a].refresh()});this.on("destroy",function(){if(this.indicators)for(var a=this.indicators.length;a--;)this.indicators[a].destroy();delete this.indicators})},_initWheel:function(){f.addEvent(this.wrapper,"mousewheel",this);f.addEvent(this.wrapper,"DOMMouseScroll",this);this.on("destroy",function(){f.removeEvent(this.wrapper,"mousewheel",this);f.removeEvent(this.wrapper,"DOMMouseScroll",
this)})},_wheel:function(a){if(this.enabled){a.preventDefault();var e,b,d,f=this;clearTimeout(this.wheelTimeout);this.wheelTimeout=setTimeout(function(){f._execEvent("scrollEnd")},400);if("wheelDeltaX"in a)e=a.wheelDeltaX/120,a=a.wheelDeltaY/120;else if("wheelDelta"in a)e=a=a.wheelDelta/120;else if("detail"in a)e=a=-a.detail/3;else return;e*=this.options.mouseWheelSpeed;a*=this.options.mouseWheelSpeed;this.hasVerticalScroll||(e=a,a=0);this.options.snap?(b=this.currentPage.pageX,d=this.currentPage.pageY,
0<e?b--:0>e&&b++,0<a?d--:0>a&&d++,this.goToPage(b,d)):(b=this.x+c.round(this.hasHorizontalScroll?e*this.options.invertWheelDirection:0),d=this.y+c.round(this.hasVerticalScroll?a*this.options.invertWheelDirection:0),0<b?b=0:b<this.maxScrollX&&(b=this.maxScrollX),0<d?d=0:d<this.maxScrollY&&(d=this.maxScrollY),this.scrollTo(b,d,0))}},_initSnap:function(){this.currentPage={};"string"==typeof this.options.snap&&(this.options.snap=this.scroller.querySelectorAll(this.options.snap));this.on("refresh",function(){var a=
0,e,b=0,d,f,g,h=0,l;d=this.options.snapStepX||this.wrapperWidth;var w=this.options.snapStepY||this.wrapperHeight;this.pages=[];if(this.wrapperWidth&&this.wrapperHeight&&this.scrollerWidth&&this.scrollerHeight){if(!0===this.options.snap){f=c.round(d/2);for(g=c.round(w/2);h>-this.scrollerWidth;){this.pages[a]=[];for(l=e=0;l>-this.scrollerHeight;)this.pages[a][e]={x:c.max(h,this.maxScrollX),y:c.max(l,this.maxScrollY),width:d,height:w,cx:h-f,cy:l-g},l-=w,e++;h-=d;a++}}else{w=this.options.snap;e=w.length;
for(d=-1;a<e;a++){if(0===a||w[a].offsetLeft<=w[a-1].offsetLeft)b=0,d++;this.pages[b]||(this.pages[b]=[]);h=c.max(-w[a].offsetLeft,this.maxScrollX);l=c.max(-w[a].offsetTop,this.maxScrollY);f=h-c.round(w[a].offsetWidth/2);g=l-c.round(w[a].offsetHeight/2);this.pages[b][d]={x:h,y:l,width:w[a].offsetWidth,height:w[a].offsetHeight,cx:f,cy:g};h>this.maxScrollX&&b++}}this.goToPage(this.currentPage.pageX||0,this.currentPage.pageY||0,0);0===this.options.snapThreshold%1?this.snapThresholdY=this.snapThresholdX=
this.options.snapThreshold:(this.snapThresholdX=c.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].width*this.options.snapThreshold),this.snapThresholdY=c.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].height*this.options.snapThreshold))}});this.on("flick",function(){var a=this.options.snapSpeed||c.max(c.max(c.min(c.abs(this.x-this.startX),1E3),c.min(c.abs(this.y-this.startY),1E3)),300);this.goToPage(this.currentPage.pageX+this.directionX,this.currentPage.pageY+this.directionY,
a)})},_nearestSnap:function(a,e){if(!this.pages.length)return{x:0,y:0,pageX:0,pageY:0};var b=0,d=this.pages.length,f=0;if(c.abs(a-this.absStartX)<this.snapThresholdX&&c.abs(e-this.absStartY)<this.snapThresholdY)return this.currentPage;0<a?a=0:a<this.maxScrollX&&(a=this.maxScrollX);0<e?e=0:e<this.maxScrollY&&(e=this.maxScrollY);for(;b<d;b++)if(a>=this.pages[b][0].cx){a=this.pages[b][0].x;break}for(d=this.pages[b].length;f<d;f++)if(e>=this.pages[0][f].cy){e=this.pages[0][f].y;break}b==this.currentPage.pageX&&
(b+=this.directionX,0>b?b=0:b>=this.pages.length&&(b=this.pages.length-1),a=this.pages[b][0].x);f==this.currentPage.pageY&&(f+=this.directionY,0>f?f=0:f>=this.pages[0].length&&(f=this.pages[0].length-1),e=this.pages[0][f].y);return{x:a,y:e,pageX:b,pageY:f}},goToPage:function(a,e,b,d){d=d||this.options.bounceEasing;a>=this.pages.length?a=this.pages.length-1:0>a&&(a=0);e>=this.pages[a].length?e=this.pages[a].length-1:0>e&&(e=0);var f=this.pages[a][e].x,g=this.pages[a][e].y;b=void 0===b?this.options.snapSpeed||
c.max(c.max(c.min(c.abs(f-this.x),1E3),c.min(c.abs(g-this.y),1E3)),300):b;this.currentPage={x:f,y:g,pageX:a,pageY:e};this.scrollTo(f,g,b,d)},next:function(a,e){var b=this.currentPage.pageX,c=this.currentPage.pageY;b++;b>=this.pages.length&&this.hasVerticalScroll&&(b=0,c++);this.goToPage(b,c,a,e)},prev:function(a,b){var c=this.currentPage.pageX,d=this.currentPage.pageY;c--;0>c&&this.hasVerticalScroll&&(c=0,d--);this.goToPage(c,d,a,b)},_initKeys:function(a){a={pageUp:33,pageDown:34,end:35,home:36,left:37,
up:38,right:39,down:40};var e;if("object"==typeof this.options.keyBindings)for(e in this.options.keyBindings)"string"==typeof this.options.keyBindings[e]&&(this.options.keyBindings[e]=this.options.keyBindings[e].toUpperCase().charCodeAt(0));else this.options.keyBindings={};for(e in a)this.options.keyBindings[e]=this.options.keyBindings[e]||a[e];f.addEvent(b,"keydown",this);this.on("destroy",function(){f.removeEvent(b,"keydown",this)})},_key:function(a){if(this.enabled){var b=this.options.snap,d=b?
this.currentPage.pageX:this.x,g=b?this.currentPage.pageY:this.y,h=f.getTime(),l=this.keyTime||0,n;this.options.useTransition&&this.isInTransition&&(n=this.getComputedPosition(),this._translate(c.round(n.x),c.round(n.y)),this.isInTransition=!1);this.keyAcceleration=200>h-l?c.min(this.keyAcceleration+0.25,50):0;switch(a.keyCode){case this.options.keyBindings.pageUp:this.hasHorizontalScroll&&!this.hasVerticalScroll?d+=b?1:this.wrapperWidth:g+=b?1:this.wrapperHeight;break;case this.options.keyBindings.pageDown:this.hasHorizontalScroll&&
!this.hasVerticalScroll?d-=b?1:this.wrapperWidth:g-=b?1:this.wrapperHeight;break;case this.options.keyBindings.end:d=b?this.pages.length-1:this.maxScrollX;g=b?this.pages[0].length-1:this.maxScrollY;break;case this.options.keyBindings.home:g=d=0;break;case this.options.keyBindings.left:d+=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.up:g+=b?1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.right:d-=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.down:g-=
b?1:5+this.keyAcceleration>>0;break;default:return}b?this.goToPage(d,g):(0<d?this.keyAcceleration=d=0:d<this.maxScrollX&&(d=this.maxScrollX,this.keyAcceleration=0),0<g?this.keyAcceleration=g=0:g<this.maxScrollY&&(g=this.maxScrollY,this.keyAcceleration=0),this.scrollTo(d,g,0),this.keyTime=h)}},_animate:function(a,b,c,d){function g(){var H=f.getTime(),L;H>=W?(l.isAnimating=!1,l._translate(a,b),l.resetPosition(l.options.bounceTime)||l._execEvent("scrollEnd")):(H=(H-w)/c,L=d(H),H=(a-n)*L+n,L=(b-m)*L+
m,l._translate(H,L),l.isAnimating&&h(g))}var l=this,n=this.x,m=this.y,w=f.getTime(),W=w+c;this.isAnimating=!0;g()},handleEvent:function(a){switch(a.type){case "touchstart":case "MSPointerDown":case "mousedown":this._start(a);break;case "touchmove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "MSPointerUp":case "mouseup":case "touchcancel":case "MSPointerCancel":case "mousecancel":this._end(a);break;case "orientationchange":case "resize":this._resize();break;case "transitionend":case "webkitTransitionEnd":case "oTransitionEnd":case "MSTransitionEnd":this._transitionEnd(a);
break;case "DOMMouseScroll":case "mousewheel":this._wheel(a);break;case "keydown":this._key(a);break;case "click":a._constructed||(a.preventDefault(),a.stopPropagation())}}};m.prototype={handleEvent:function(a){switch(a.type){case "touchstart":case "MSPointerDown":case "mousedown":this._start(a);break;case "touchmove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "MSPointerUp":case "mouseup":case "touchcancel":case "MSPointerCancel":case "mousecancel":this._end(a)}},
destroy:function(){this.options.interactive&&(f.removeEvent(this.indicator,"touchstart",this),f.removeEvent(this.indicator,"MSPointerDown",this),f.removeEvent(this.indicator,"mousedown",this),f.removeEvent(b,"touchmove",this),f.removeEvent(b,"MSPointerMove",this),f.removeEvent(b,"mousemove",this),f.removeEvent(b,"touchend",this),f.removeEvent(b,"MSPointerUp",this),f.removeEvent(b,"mouseup",this));this.options.defaultScrollbars&&this.wrapper.parentNode.removeChild(this.wrapper)},_start:function(a){var c=
a.touches?a.touches[0]:a;a.preventDefault();a.stopPropagation();this.transitionTime(0);this.initiated=!0;this.moved=!1;this.lastPointX=c.pageX;this.lastPointY=c.pageY;this.startTime=f.getTime();this.options.disableTouch||f.addEvent(b,"touchmove",this);this.options.disablePointer||f.addEvent(b,"MSPointerMove",this);this.options.disableMouse||f.addEvent(b,"mousemove",this);this.scroller._execEvent("beforeScrollStart")},_move:function(a){var b=a.touches?a.touches[0]:a,c,d;f.getTime();this.moved||this.scroller._execEvent("scrollStart");
this.moved=!0;c=b.pageX-this.lastPointX;this.lastPointX=b.pageX;d=b.pageY-this.lastPointY;this.lastPointY=b.pageY;this._pos(this.x+c,this.y+d);a.preventDefault();a.stopPropagation()},_end:function(a){if(this.initiated){this.initiated=!1;a.preventDefault();a.stopPropagation();f.removeEvent(b,"touchmove",this);f.removeEvent(b,"MSPointerMove",this);f.removeEvent(b,"mousemove",this);if(this.scroller.options.snap){a=this.scroller._nearestSnap(this.scroller.x,this.scroller.y);var e=this.options.snapSpeed||
c.max(c.max(c.min(c.abs(this.scroller.x-a.x),1E3),c.min(c.abs(this.scroller.y-a.y),1E3)),300);if(this.scroller.x!=a.x||this.scroller.y!=a.y)this.scroller.directionX=0,this.scroller.directionY=0,this.scroller.currentPage=a,this.scroller.scrollTo(a.x,a.y,e,this.scroller.options.bounceEasing)}this.moved&&this.scroller._execEvent("scrollEnd")}},transitionTime:function(a){this.indicatorStyle[f.style.transitionDuration]=(a||0)+"ms"},transitionTimingFunction:function(a){this.indicatorStyle[f.style.transitionTimingFunction]=
a},refresh:function(){this.transitionTime(0);this.indicatorStyle.display=this.options.listenX&&!this.options.listenY?this.scroller.hasHorizontalScroll?"block":"none":this.options.listenY&&!this.options.listenX?this.scroller.hasVerticalScroll?"block":"none":this.scroller.hasHorizontalScroll||this.scroller.hasVerticalScroll?"block":"none";this.scroller.hasHorizontalScroll&&this.scroller.hasVerticalScroll?(f.addClass(this.wrapper,"iScrollBothScrollbars"),f.removeClass(this.wrapper,"iScrollLoneScrollbar"),
this.options.defaultScrollbars&&this.options.customStyle&&(this.options.listenX?this.wrapper.style.right="8px":this.wrapper.style.bottom="8px")):(f.removeClass(this.wrapper,"iScrollBothScrollbars"),f.addClass(this.wrapper,"iScrollLoneScrollbar"),this.options.defaultScrollbars&&this.options.customStyle&&(this.options.listenX?this.wrapper.style.right="2px":this.wrapper.style.bottom="2px"));this.options.listenX&&(this.wrapperWidth=this.wrapper.clientWidth,this.options.resize?(this.indicatorWidth=c.max(c.round(this.wrapperWidth*
this.wrapperWidth/(this.scroller.scrollerWidth||this.wrapperWidth||1)),8),this.indicatorStyle.width=this.indicatorWidth+"px"):this.indicatorWidth=this.indicator.clientWidth,this.maxPosX=this.wrapperWidth-this.indicatorWidth,this.sizeRatioX=this.options.speedRatioX||this.scroller.maxScrollX&&this.maxPosX/this.scroller.maxScrollX);this.options.listenY&&(this.wrapperHeight=this.wrapper.clientHeight,this.options.resize?(this.indicatorHeight=c.max(c.round(this.wrapperHeight*this.wrapperHeight/(this.scroller.scrollerHeight||
this.wrapperHeight||1)),8),this.indicatorStyle.height=this.indicatorHeight+"px"):this.indicatorHeight=this.indicator.clientHeight,this.maxPosY=this.wrapperHeight-this.indicatorHeight,this.sizeRatioY=this.options.speedRatioY||this.scroller.maxScrollY&&this.maxPosY/this.scroller.maxScrollY);this.updatePosition()},updatePosition:function(){var a=c.round(this.sizeRatioX*this.scroller.x)||0,b=c.round(this.sizeRatioY*this.scroller.y)||0;this.options.ignoreBoundaries||(0>a?a=0:a>this.maxPosX&&(a=this.maxPosX),
0>b?b=0:b>this.maxPosY&&(b=this.maxPosY));this.x=a;this.y=b;var d=!1;this.scroller.options.indicators&&(d=this.scroller.options.indicators[0].notUseTransform);this.scroller.options.useTransform&&!d?this.indicatorStyle[f.style.transform]="translate("+a+"px,"+b+"px)"+this.scroller.translateZ:(this.indicatorStyle.webkitTransition="",this.indicatorStyle.left=a+"px",this.indicatorStyle.top=b+"px",this.indicatorStyle.position="relative")},_pos:function(a,b){0>a?a=0:a>this.maxPosX&&(a=this.maxPosX);0>b?
b=0:b>this.maxPosY&&(b=this.maxPosY);a=this.options.listenX?c.round(a/this.sizeRatioX):this.scroller.x;b=this.options.listenY?c.round(b/this.sizeRatioY):this.scroller.y;this.scroller.scrollTo(a,b)}};g.ease=f.ease;return g}(window,document,Math);(function(){function b(a){var b=K,c;a:{c=b.className.split(/\s+/);for(var e=0,d=c.length;e<d;e+=1)if(c[e]===a){c=!0;break a}c=!1}c||(b.className+=(""===b.className?"":" ")+a)}function d(a,b,c){this.b=null!=a?a:null;this.c=null!=b?b:null;this.e=null!=c?c:null}function c(a,b){return a.b>b.b||a.b===b.b&&a.c>b.c||a.b===b.b&&a.c===b.c&&a.e>b.e?1:a.b<b.b||a.b===b.b&&a.c<b.c||a.b===b.b&&a.c===b.c&&a.e<b.e?-1:0}function g(a,b){return 0===c(a,b)||1===c(a,b)}function l(){var a=f.exec(n[1]),b=null,c=null,e=
null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(c=parseInt(a[2],10)),null!==a[3]&&a[3]&&(e=parseInt(a[3],10)));return new d(b,c,e)}function m(){var b=a;return 3===b.a||7===b.a||6===b.a||9===b.a||8===b.a||5===b.a?"grayscale":1===b.a&&g(b.f,new d(6,2))&&1===b.d?"grayscale":"unknown"}var h=window,f=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/,a,e=h.navigator.userAgent,u=0,v=new d,p=0,O=new d,n=null;if(n=/(?:iPod|iPad|iPhone).*? OS ([\d_]+)/.exec(e))p=3,O=
l();else if(n=/(?:BB\d{2}|BlackBerry).*?Version\/([^\s]*)/.exec(e))p=9,O=l();else if(n=/Android ([^;)]+)|Android/.exec(e))p=5,O=l();else if(n=/Windows Phone(?: OS)? ([^;)]+)/.exec(e))p=8,O=l();else if(n=/Linux ([^;)]+)|Linux/.exec(e))p=4,O=l();else if(n=/OS X ([^;)]+)/.exec(e))p=2,O=l();else if(n=/Windows NT ([^;)]+)/.exec(e))p=1,O=l();else if(n=/CrOS ([^;)]+)/.exec(e))p=6,O=l();if(n=/MSIE ([\d\w\.]+)/.exec(e))u=1,v=l();else if(n=/Trident.*rv:([\d\w\.]+)/.exec(e))u=1,v=l();else if(n=/OPR\/([\d.]+)/.exec(e))u=
4,v=l();else if(n=/Opera Mini.*Version\/([\d\.]+)/.exec(e))u=4,v=l();else if(n=/Opera(?: |.*Version\/|\/)([\d\.]+)/.exec(e))u=4,v=l();else if(n=/Firefox\/([\d\w\.]+)|Firefox/.exec(e))u=3,v=l();else if(n=/(?:Chrome|CrMo|CriOS)\/([\d\.]+)/.exec(e))u=2,v=l();else if(n=/Silk\/([\d\._]+)/.exec(e))u=7,v=l();else if(5===p||9===p)u=6;else if(n=/Version\/([\d\.\w]+).*Safari/.exec(e))u=5,v=l();a=new function(a,b,c,e){this.d=a;this.g=b;this.a=c;this.f=e}(u,v,p,O);var e=m(),u=m(),u="unknown"!==u?u:2===a.a||4===
a.a?"subpixel":1===a.a?g(a.f,new d(6,0))?"subpixel":1===a.d?g(a.g,new d(7,0))?"subpixel":"grayscale":"subpixel":"unknown",K=h.document.documentElement;if(1===a.a){if(!(h=2===a.d))(h=4===a.d)||(h=-1===c(a.f,new d(6,0)));if(h)h="gdi";else if(g(a.f,new d(6,0))){if(h=1===a.d)h=a.g,v=new d(8,0),h=0===c(h,v)||-1===c(h,v);h=h?"gdi":"directwrite"}else h="unknown"}else h=8===a.a?"directwrite":2===a.a||3===a.a?"coretext":5===a.a||4===a.a||6===a.a||7===a.a||9===a.a?"freetype":"unknown";b("tr-"+h);"unknown"===
e&&"unknown"!==u&&(e+="-"+u);b("tr-aa-"+e)})();/*
 FTScroller is (c) 2012 The Financial Times Ltd [All rights reserved] and licensed under the MIT license.

 Inspired by Uxebu TouchScroll, (c) 2010 uxebu Consulting Ltd. & Co. KG and David Aurelio, which is BSD licensed (https://github.com/davidaurelio/TouchScroll)
 Inspired by Zynga Scroller, (c) 2011 Zynga Inc and Deutsche Telekom AG, which is MIT licensed (https://github.com/zynga/scroller)
 Includes CubicBezier, (c) 2008 Apple Inc [All rights reserved], (c) 2010 David Aurelio and uxebu Consulting Ltd. & Co. KG. [All rights reserved], which is 2-clause BSD licensed (see above or https://github.com/davidaurelio/TouchScroll).
 The Financial Times Ltd [All rights reserved]
 @codingstandard ftlabs-jslint
 @version 0.3.2
*/
var FTScroller,CubicBezier;
(function(){var b=!1,d=window.navigator.msPointerEnabled,c=!d&&(window.propertyIsEnumerable("ontouchstart")||window.document.hasOwnProperty("ontouchstart")),g=!window.hasOwnProperty("ArrayBuffer"),l=window.Selection&&window.Selection.prototype.removeAllRanges,m,h,f;void 0!==document.createElement("div").style.transform?(h=m="",f="transform"):window.opera&&"[object Opera]"===Object.prototype.toString.call(window.opera)?(m="-o-",h="O",f="OTransform"):void 0!==document.documentElement.style.MozTransform?(m=
"-moz-",h="Moz",f="MozTransform"):void 0!==document.documentElement.style.webkitTransform?(m="-webkit-",h="webkit",f="-webkit-transform"):"string"===typeof navigator.cpuClass&&(m="-ms-",h="ms",f="-ms-transform");if(!g&&void 0===document.createElement("div").style[h+(h?"P":"p")+"erspective"])g=!0;var a=h+(h?"T":"t")+"ransform",e=h+(h?"T":"t")+"ransition",u=g?"translate(":"translate3d(",v={x:"",y:"0,"},p={x:",0"+(g?")":",0)"),y:g?")":",0)"};FTScroller=function(g,n){var K,w,W,H,L,P,Ma,Na,$,ra,Oa,sa,
Pa,Qa,U,da,ta,Ra,aa,N,X,ua,I,va,wa,Sa,Ta,xa,ba,ya,Ua,Va,za,Wa,ja,Aa,Xa,Ya,Za,$a,Ba,ka,Ca,Da,la,Ea,k={index:"",scrollbars:!0,scrollingX:!0,scrollingY:!0,scrollBoundary:1,scrollResponseBoundary:1,alwaysScroll:!1,contentWidth:void 0,contentHeight:void 0,snapping:!1,snapSizeX:void 0,snapSizeY:void 0,paginatedSnap:!1,bouncing:!0,flinging:!0,updateOnChanges:!0,updateOnWindowResize:!1,baseAlignments:{x:-1,y:-1},windowScrollingActiveFlag:void 0,hwAccelerationClass:"ftscroller_hwaccelerated",enableRequestAnimationFrameSupport:!0,
maxFlingDuration:300,disabledInputMethods:{mouse:!1,touch:!1,scroll:!1},scrollingClassName:void 0,flingBezier:new CubicBezier(0,0.5,0.5,1),bounceDecelerationBezier:new CubicBezier(0,0,0,0.9),bounceBezier:new CubicBezier(0,0,0,0)},ab,ma=this,Q=g,q,A,F={x:null,y:null},C={x:null,y:null},B={x:null,y:null},z={x:null,y:null,rawX:null,rawY:null},y={x:null,y:null},r={x:!1,y:!1,userX:!1,userY:!1},Fa={x:0,y:0},ea={x:0,y:0},Ga=0,Ha=0,x=!1,fa=0,ga=!1,R=!1,Y=!1,na=!1,D={x:0,y:0},s={x:0,y:0},J={x:0,y:0},bb={x:null,
y:null},ha=!1,G=[],Ia=!1,V={},t={x:!0,y:!0},Ja=0,Ka=0,oa=0,pa=0,E=[],S=!1,La=!1,ia=!1,Z=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||!1,qa=window.cancelAnimationFrame||window.cancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.msCancelAnimationFrame||window.msCancelRequestAnimationFrame||
!1,M={scrollstart:[],scroll:[],scrollend:[],segmentwillchange:[],segmentdidchange:[],reachedstart:[],reachedend:[],scrollinteractionend:[]},ca;if("object"===typeof FTScrollerOptions&&FTScrollerOptions)for(K in FTScrollerOptions)FTScrollerOptions.hasOwnProperty(K)&&k.hasOwnProperty(K)&&(k[K]=FTScrollerOptions[K]);if(n){for(K in n)n.hasOwnProperty(K)&&k.hasOwnProperty(K)&&(k[K]=n[K]);n.hasOwnProperty("snapSizeX")&&!isNaN(n.snapSizeX)&&(r.userX=r.x=n.snapSizeX);n.hasOwnProperty("snapSizeY")&&!isNaN(n.snapSizeY)&&
(r.userY=r.y=n.snapSizeY);n.contentWidth&&n.contentHeight&&(n.updateOnChanges=!1)}k.scrollResponseBoundary=Math.min(k.scrollBoundary,k.scrollResponseBoundary);k.scrollingX&&(V.x=!0);k.scrollingY&&(V.y=!0);qa=(Z=k.enableRequestAnimationFrameSupport&&Z)&&qa;w=function(a,b,c){var e,d,f=0,g={};L(Date.now());e={x:-a,y:-b};for(d in V)V.hasOwnProperty(d)&&(a=e[d],!1!==a&&(a=Math.min(0,Math.max(y[d],a)),k.snapping&&r[d]&&(a=Math.round(a/r[d])*r[d]),b=c||0,!0===b&&(b=20*Math.sqrt(Math.abs(D[d]-a))),N(d,a,
b),g[d]=a,f=Math.max(f,b)));if(D.x!==e.x||D.y!==e.y)Ia=!0,I("scrollstart",X()),I("scroll",X());f?G.push(setTimeout(function(){for(var a in g)g.hasOwnProperty(a)&&(s[a]=g[a]);P()},f)):P()};W=function(a,b,c,e){var d=na;0>=c&&(c=Date.now());if(k.windowScrollingActiveFlag&&window[k.windowScrollingActiveFlag])return!1;d?Ma():ha=!1;Ja=a;Ka=b;J.x=s.x;J.y=s.y;E.length=0;E.push({x:a,y:b,t:c});d&&H(a,b,c,e,d);return!0};H=function(a,c,e,d,f){var g,h,n=!1,m=a-Ja,p=c-Ka;0>=e&&(e=Date.now());J.x=D.x+m;J.y=D.y+
p;if(!R&&(b&&b!==ma?h=!0:k.windowScrollingActiveFlag&&window[k.windowScrollingActiveFlag]&&(h=!0),h)){la();x=!1;Y&&(ba(),$(!0)||P(!0));return}if(Y)d.preventDefault();else{h=Sa(J);(k.bouncing||f||t.x&&m&&0>h.x||t.y&&p&&0>h.y)&&d.preventDefault();if(!f&&(!t.x||Math.abs(m)<k.scrollResponseBoundary)&&(!t.y||Math.abs(p)<k.scrollResponseBoundary))return;if(!k.bouncing&&!f&&(!t.x||!m||0<h.x)&&(!t.y||!p||0<h.y)){ha=!0;return}Ta();n=na=Ia=Y=!0}if(!R&&(f&&k.snapping||t.x&&Math.abs(m)>=k.scrollBoundary||t.y&&
Math.abs(p)>=k.scrollBoundary))R=!0,b=ma,k.windowScrollingActiveFlag&&(window[k.windowScrollingActiveFlag]=ma),I("scrollstart",X());R&&Da();l&&window.getSelection().removeAllRanges();sa();if(n&&(k.scrollingClassName&&(q.className+=" "+k.scrollingClassName),k.scrollbars))for(g in t)t.hasOwnProperty(g)&&(C[g].className+=" active");E.push({x:a,y:c,t:e});30<E.length&&E.splice(0,15)};L=function(a,c){la();x=!1;ba();I("scrollinteractionend",{});R?(E[E.length-1].t=a,b=Y=R=!1,k.windowScrollingActiveFlag&&
(window[k.windowScrollingActiveFlag]=!1),ha=!0,c&&c.preventDefault(),!Na()&&!$()&&P()):!$(!0)&&Y&&P(!0)};P=function(a){var b,c;Y=na=!1;k.scrollingClassName&&(c=RegExp("(?:^|\\s)"+k.scrollingClassName+"(?!\\S)","g"),q.className=q.className.replace(c,""));if(k.scrollbars)for(b in t)t.hasOwnProperty(b)&&(C[b].className=C[b].className.replace(/ ?active/g,""));D.x=s.x;D.y=s.y;c=X();a||(I("scroll",c),aa(!0));c.cancelled=a;I("scrollend",c);for(b in t)t.hasOwnProperty(b)&&(F[b].style[e]="",k.scrollbars&&
(C[b].style[e]=""));a=0;for(b=G.length;a<b;a+=1)window.clearTimeout(G[a]);G.length=0};Ma=function(){var a,b;na=!1;Ra();for(a in t)t.hasOwnProperty(a)&&N(a,D[a],16,k.bounceDecelerationBezier);aa(!1);a=0;for(b=G.length;a<b;a+=1)window.clearTimeout(G[a]);G.length=0};Na=function(){var a,b,c,e,d,f,g,h,l,n,m,p,q,w=0,u=!1,v={};if(1===E.length||!k.flinging||"scrollwheel"===x)return!1;for(b in t)if(t.hasOwnProperty(b)){h=350;g=0;l=n=!1;p=void 0;m=k.flingBezier;e=E[E.length-1];d=E[E.length-2];for(a=E.length-
3;0<=a&&!(100<e.t-E[a].t);a-=1)d=E[a];(a=e.t-d.t)||(a=16);c=(e[b]-d[b])/a;0.2>Math.abs(c)?a=e=0:(e=Math.log(0.2/Math.abs(c))/Math.log(0.996),a=c*(1-Math.pow(0.996,e+1))/(1-0.996));d=Math.floor(s[b]+a);k.bouncing||(0===s[b]&&0<d?d=0:s[b]===y[b]&&d<s[b]&&(d=s[b]));k.paginatedSnap&&k.snapping?(q=-s[b]/r[b],q=ea[b]<q?Math.floor(q):Math.ceil(q),d>-(q-1)*r[b]?g=d+(q-1)*r[b]:d<-(q+1)*r[b]?g=d+(q+1)*r[b]:0.2<Math.abs(c)&&(d=0>c?Math.floor(s[b]/r[b])*r[b]:Math.ceil(s[b]/r[b])*r[b],e=Math.min(k.maxFlingDuration,
e*(d-s[b])/a))):k.snapping&&(g=d-Math.round(d/r[b])*r[b]);0<d-g?(g=d,n=!0):d-g<y[b]&&(g=d-y[b],n=!0);if(g)if(n&&k.bouncing&&a)a=Math.floor(a),f=0<d?d-Math.max(0,s[b]):d-Math.min(y[b],s[b]),n=a-f,!a||!e?a=0:(a=m._getCoordinateForT(m.getTForY((a-f)/a,1/e),m._p1.x,m._p2.x),p=a*e),c=Math.ceil(f/8),Math.abs(c)>B[b]/2&&(c=0>c?-Math.floor(B[b]/2):Math.floor(B[b]/2)),l=0<d?0:y[b],0===a?(e/=6,d=s[b]+n+c,f=e):(f=(a+(1-a)/6)*e,ua(b,s[b]+n+c,(1-a)*e/6,k.bounceDecelerationBezier,p),m=m.divideAtX(f/e,1/e)[0],e=
f,d=s[b]+n+c);else if(0>a&&g<a||0<a&&g>a)d-=Math.floor(a/2),g-=Math.floor(a/2),h=50*Math.sqrt(Math.abs(g)),l=d-g,e=350,f=0.97*e;else{d-=g;if(a){if(0>a&&0>g||0<a&&0<g)a=m._getCoordinateForT(m.getTForY((Math.abs(a)-Math.abs(g))/Math.abs(a),1/e),m._p1.x,m._p2.x),m=m.divideAtX(a,1/e)[0],e=Math.round(e*a)}else e=h;h=g=0}if(d!==s[b]||g)u=!0,N(b,d,e,m,p),g&&h&&ua(b,l,h,k.bounceBezier,f),w=Math.max(w,g?f+h:e),v[b]=!1===l?d:l}u&&w&&G.push(setTimeout(function(){for(var a in v)v.hasOwnProperty(a)&&(s[a]=v[a]);
P()},w));return u};$=function(a){var b,c=a?100:350,d=s;k.snapping&&(Fa=Oa(d),d=ra(Fa,d));var d=Pa(d),e=!1;for(b in V)V.hasOwnProperty(b)&&d[b]!==s[b]&&(e=!0);if(!e)return!1;for(b in V)V.hasOwnProperty(b)&&N(b,d[b],c);G.push(setTimeout(function(){s=d;P(a)},c));return!0};Oa=function(a){var b,c={x:0,y:0};for(b in t)t.hasOwnProperty(b)&&r[b]&&(c[b]=Math.round(a[b]/r[b]));return c};ra=function(a,b){var c,d={x:b.x,y:b.y};for(c in t)t.hasOwnProperty(c)&&(d[c]=a[c]*r[c]);return d};sa=function(){for(var a in t)t.hasOwnProperty(a)&&
(0<J[a]?J[a]=wa(J[a],a):J[a]<y[a]&&(J[a]=y[a]+wa(J[a]-y[a],a)));Z||xa()};Pa=function(a){var b,c={x:a.x,y:a.y};for(b in t)t.hasOwnProperty(b)&&(0<a[b]?c[b]=0:a[b]<y[b]&&(c[b]=y[b]));return c};Qa=function(){var a,b,c,d,e,f,g,h,l;if((a=Q.firstElementChild)&&-1!==a.className.indexOf("ftscroller_container")){if(k.scrollingX){b=a.firstElementChild;if(!b||-1===b.className.indexOf("ftscroller_x"))return;d=b;if(k.scrollbars){if(g=a.getElementsByClassName("ftscroller_scrollbarx")){h=0;for(l=g.length;h<l;h+=
1)if(g[h].parentNode===a){e=g[h];break}}if(!e)return}}else d=a;if(k.scrollingY){c=d.firstElementChild;if(!c||-1===c.className.indexOf("ftscroller_y"))return;if(k.scrollbars){if(g=a.getElementsByClassName("ftscroller_scrollbary")){h=0;for(l=g.length;h<l;h+=1)if(g[h].parentNode===a){f=g[h];break}}if(!f)return}}q=a;b&&(F.x=b);c&&(F.y=c);e&&(C.x=e);f&&(C.y=f);A=k.scrollingY?c:b;return!0}};U=function(a){S&&window.clearTimeout(S);a&&"resize"===a.type?da():S=setTimeout(function(){da()},100)};da=function(a){var b;
if(!q||!A)return!1;S&&(window.clearTimeout(S),S=!1);var c,d,e;e={x:!1,y:!1};for(b in e)e.hasOwnProperty(b)&&(0===s[b]?e[b]=-1:s[b]<=y[b]?e[b]=1:2*s[b]<=y[b]+5&&2*s[b]>=y[b]-5&&(e[b]=0));c=q.offsetWidth;d=q.offsetHeight;var f=n.contentWidth||A.offsetWidth,g=n.contentHeight||A.offsetHeight,h=f,l=g,m={x:!1,y:!1};r.userX||(r.x=c);r.userY||(r.y=d);k.snapping&&(h=r.userX?Math.ceil(h/r.userX)*r.userX:Math.ceil(h/r.x)*r.x,l=r.userY?Math.ceil(l/r.userY)*r.userY:Math.ceil(l/r.y)*r.y);if(!(B.x===c&&B.y===d&&
z.x===h&&z.y===l))if(B.x=c,B.y=d,z.x=h,z.rawX=f,z.y=l,z.rawY=g,y.x=c-h,y.y=d-l,ta(),R)s.x--,s.y--,sa();else{!a&&k.snapping&&(aa(),m=ra(Fa,s));for(b in m)m.hasOwnProperty(b)&&!(B[b]<z[b]&&Ia&&k.baseAlignments[b]!==e[b])&&(1===k.baseAlignments[b]?m[b]=y[b]:0===k.baseAlignments[b]?m[b]=Math.floor(y[b]/2):-1===k.baseAlignments[b]&&(m[b]=0));k.scrollingX&&!1!==m.x&&(N("x",m.x,0),D.x=m.x);k.scrollingY&&!1!==m.y&&(N("y",m.y,0),D.y=m.y)}};ta=function(){k.scrollbars&&(k.scrollingX&&(C.x.style.width=Math.max(6,
Math.round(B.x*(B.x/z.x)-4))+"px"),k.scrollingY&&(C.y.style.height=Math.max(6,Math.round(B.y*(B.y/z.y)-4))+"px"));t={};if(k.scrollingX&&(z.x>B.x||k.alwaysScroll))t.x=!0;if(k.scrollingY&&(z.y>B.y||k.alwaysScroll))t.y=!0};Ra=function(){var a,b;for(a in t)t.hasOwnProperty(a)&&(b=window.getComputedStyle(F[a],null)[f],b=b.split(", "),D[a]=6===b.length?parseInt(b["y"===a?5:4],10):parseInt(b["y"===a?13:12],10),s[a]=D[a])};aa=function(a){var b,c={x:0,y:0};if(k.snapping){for(b in t)t.hasOwnProperty(b)&&(c[b]=
Math.max(0,Math.min(Math.ceil(z[b]/r[b])-1,Math.round(-s[b]/r[b]))));if(c.x!==Ga||c.y!==Ha)Ga=c.x,Ha=c.y,I("segmentwillchange",{segmentX:c.x,segmentY:c.y});if(a&&(c.x!==ea.x||c.y!==ea.y))ea.x=c.x,ea.y=c.y,I("segmentdidchange",{segmentX:c.x,segmentY:c.y})}};N=function(b,c,d,f,g){var h=null;if(!F[b])return!1;d?(f||(f=k.flingBezier),f=m+"transform "+d+"ms "+f.toString()):f="";F[b].style[e]=f;k.scrollbars&&(C[b].style[e]=f);F[b].style[a]=u+v[b]+c+"px"+p[b];k.scrollbars&&(C[b].style[a]=u+v[b]+-c*B[b]/
z[b]+"px"+p[b]);0<=c?h="start":c<=y[b]&&(h="end");h!==bb[b]&&(null!==h&&(d?G.push(setTimeout(function(){I("reached"+h,{axis:b,index:k.index})},g||d)):I("reached"+h,{axis:b,index:k.index})),bb[b]=h);d||(s[b]=c)};X=function(){return{scrollLeft:-s.x,scrollTop:-s.y}};ua=function(a,b,c,d,e){G.push(setTimeout(function(){N(a,b,c,d)},e))};I=function(a,b){var c,d;b.srcObject=ab;c=0;for(d=M[a].length;c<d;c+=1)try{M[a][c](b)}catch(e){window.console&&window.console.error&&window.console.error(e.message+" ("+
e.sourceURL+", line "+e.line+")")}};va=function(a){var b,c;a=Ea(a.target);var d=Ea(q),e={x:"left",y:"top"},f={x:"right",y:"bottom"},g={x:"width",y:"height"};if(!1===x){for(c in t)if(t.hasOwnProperty(c)&&!(a[e[c]]>=d[e[c]]&&a[f[c]]<=d[f[c]])){if(a[g[c]]>d[g[c]]&&(b=a[g[c]]-Math.max(0,d[e[c]]-a[e[c]])-Math.max(0,a[f[c]]-d[f[c]]),b>=d[g[c]]/2))continue;b=-Math.round(a[g[c]]/2-s[c]+a[e[c]]-d[e[c]]-d[g[c]]/2);b=Math.min(0,Math.max(y[c],b));N(c,b,0);D[c]=b}I("scroll",X())}};wa=function(a,b){if(!k.bouncing)return 0;
var c=Math.exp(a/B[b]);return Math.round(0.6*B[b]*(c-1)/(c+1))};Sa=function(a){var b,c,d={};for(b in a)a.hasOwnProperty(b)&&(c=a[b],d[b]=0<=c?c:c>y[b]?-1:y[b]-c);return d};Ta=function(){Z&&(ba(),ia=Z(xa))};xa=function cb(){var a,b;Z&&(ia=Z(cb));for(a in t)t.hasOwnProperty(a)&&J[a]!==s[a]&&(N(a,J[a]),b=!0);R&&b&&(I("scroll",X()),aa(!1))};ba=function(){!1!==ia&&qa&&(qa(ia),ia=!1)};ya=function(a){q&&(q._ftscrollerToggle=a?q.addEventListener:q.removeEventListener,d?(q._ftscrollerToggle("MSPointerDown",
Xa,!0),q._ftscrollerToggle("MSPointerMove",Ya,!0),q._ftscrollerToggle("MSPointerUp",Za,!0),q._ftscrollerToggle("MSPointerCancel",$a,!0)):(c&&!k.disabledInputMethods.touch&&(q._ftscrollerToggle("touchstart",Ua,!0),q._ftscrollerToggle("touchmove",Va,!0),q._ftscrollerToggle("touchend",za,!0),q._ftscrollerToggle("touchcancel",za,!0)),k.disabledInputMethods.mouse||(q._ftscrollerToggle("mousedown",Wa,!0),a||(document.removeEventListener("mousemove",ja,!0),document.removeEventListener("mouseup",Aa,!0)))),
k.disabledInputMethods.scroll||(q._ftscrollerToggle("DOMMouseScroll",Ca,!1),q._ftscrollerToggle("mousewheel",Ca,!1)),d?a?document.addEventListener("click",ka,!0):document.removeEventListener("click",ka,!0):q._ftscrollerToggle("click",ka,!0),a?(A.addEventListener("focus",va,!0),k.updateOnChanges&&(ca||(a=window.MutationObserver||window.WebKitMutationObserver||window[h+"MutationObserver"])&&(ca=new a(U)),ca?ca.observe(A,{childList:!0,characterData:!0,subtree:!0}):A.addEventListener("DOMSubtreeModified",
function(a){(!a||!(a.srcElement===A||-1!==a.srcElement.className.indexOf("ftscroller_")))&&U()},!0),A.addEventListener("load",U,!0)),k.updateOnWindowResize&&window.addEventListener("resize",U,!0)):(A.removeEventListener("focus",va,!0),ca?ca.disconnect():A.removeEventListener("DOMSubtreeModified",U,!0),A.removeEventListener("load",U,!0),window.removeEventListener("resize",U,!0)),delete q._ftscrollerToggle)};Ua=function(a){var b,c;if(x){b=0;for(c=a.touches.length;b<c;b+=1)a.touches[b].identifier===
x&&(fa=b)}else b=a.touches[0],x=b.identifier,fa=0,W(b.clientX,b.clientY,a.timeStamp,a)};Va=function(a){if(!1!==x){var b=a.touches[fa];H(b.clientX,b.clientY,a.timeStamp,a)}};za=function(a){var b,c;if(a.touches){b=0;for(c=a.touches.length;b<c;b+=1)if(a.touches[b].identifier===x){fa=b;return}}L(a.timeStamp,a)};Wa=function(a){a.button&&2===a.button||a.ctrlKey||(q.setCapture&&q.setCapture(),document.addEventListener("mousemove",ja,!0),document.addEventListener("mouseup",Aa,!0),x=a.button||1,fa=0,W(a.clientX,
a.clientY,a.timeStamp,a))};ja=function(a){x&&H(a.clientX,a.clientY,a.timeStamp,a)};Aa=function db(a){a.button&&a.button!==x||(document.removeEventListener("mousemove",ja,!0),document.removeEventListener("mouseup",db,!0),q.releaseCapture&&q.releaseCapture(),L(a.timeStamp,a))};Xa=function(a){if(!x){if(a.pointerType===a.MSPOINTER_TYPE_TOUCH){if(k.disabledInputMethods.touch)return}else if(k.disabledInputMethods.mouse)return;x=a.pointerId;Da();W(a.clientX,a.clientY,a.timeStamp,a)}};Ya=function(a){x===
a.pointerId&&H(a.clientX,a.clientY,a.timeStamp,a)};Za=function(a){x===a.pointerId&&L(a.timeStamp,a)};$a=function(a){L(a.timeStamp,a)};Ba=function(a){ga=!1};ka=function(a){if(!ha&&!x)return!0;a.preventDefault();a.stopPropagation();x||(ha=!1);return!1};Ca=function(a){var c,d;if("scrollwheel"!==x){if(!1!==x)return!0;x="scrollwheel";pa=oa=0;if(!W(a.clientX,a.clientY,Date.now(),a))return}a.wheelDelta?a.wheelDeltaX?(c=a.wheelDeltaX/2,d=a.wheelDeltaY/2):(c=0,d=a.wheelDelta/2):a.axis&&a.axis===a.HORIZONTAL_AXIS?
(c=-10*a.detail,d=0):(c=0,d=-10*a.detail);!k.scrollingY&&!c&&(c=d,d=0);oa=Math.round(oa+c);pa=Math.round(pa+d);H(Ja+oa,Ka+pa,a.timeStamp,a);La&&clearTimeout(La);La=setTimeout(function(){la();b=Y=R=x=!1;k.windowScrollingActiveFlag&&(window[k.windowScrollingActiveFlag]=!1);ba();$()||P()},300)};Da=function(){if(!ga&&!(!1===x||"scrollwheel"===x))d&&(q.msSetPointerCapture(x),q.addEventListener("MSLostPointerCapture",Ba,!1)),ga=!0};la=function(){ga&&(d&&(q.removeEventListener("MSLostPointerCapture",Ba,
!1),q.msReleasePointerCapture(x)),ga=!1)};Ea=function(a){if(a.getBoundingClientRect)return a.getBoundingClientRect();for(var b=0,c=0,d=a;d;)b=b+d.offsetLeft-d.scrollLeft,c=c+d.offsetTop-d.scrollTop,d=d.offsetParent;return{left:b,top:c,width:a.offsetWidth,height:a.offsetHeight}};(function(){var a,b;if(!Qa()){a=Q.ownerDocument.createDocumentFragment();b=document.createElement("DIV");a.appendChild(b);b.innerHTML=FTScroller.prototype.getPrependedHTML(!k.scrollingX,!k.scrollingY,k.hwAccelerationClass)+
FTScroller.prototype.getAppendedHTML(!k.scrollingX,!k.scrollingY,k.hwAccelerationClass,k.scrollbars);a=q=b.firstElementChild;k.scrollingX&&(F.x=q.firstElementChild,a=F.x,k.scrollbars&&(C.x=q.getElementsByClassName("ftscroller_scrollbarx")[0]));k.scrollingY?(F.y=a.firstElementChild,k.scrollbars&&(C.y=q.getElementsByClassName("ftscroller_scrollbary")[0]),A=F.y):A=F.x;for(;Q.firstChild;)A.appendChild(Q.firstChild);Q.appendChild(q)}})();da();ya(!0);return ab={destroy:function(a){var c,d;ya(!1);ba();S&&
(window.clearTimeout(S),S=!1);c=0;for(d=G.length;c<d;c+=1)window.clearTimeout(G[c]);G.length=0;if(a&&Q){for(;A.firstChild;)Q.appendChild(A.firstChild);Q.removeChild(q)}A=q=Q=null;F.x=null;F.y=null;C.x=null;C.y=null;for(c in M)M.hasOwnProperty(c)&&(M[c].length=0);b&&b===ma&&(b=!1,k.windowScrollingActiveFlag&&(window[k.windowScrollingActiveFlag]=!1))},setSnapSize:function(a,b){r.userX=a;r.userY=b;r.x=a;r.y=b;z.x=Math.ceil(z.rawX/a)*a;z.y=Math.ceil(z.rawY/b)*b;y.x=B.x-z.x;y.y=B.y-z.y;ta();$();aa(!0)},
scrollTo:w,scrollBy:function(a,b,c){w(parseFloat(a)-D.x,parseFloat(b)-D.y,c)},updateDimensions:function(a,b,c){n.contentWidth=a||n.contentWidth;n.contentHeight=b||n.contentHeight;da(!!c)},addEventListener:function(a,b){if(!M.hasOwnProperty(a))return!1;M[a].push(b);return!0},removeEventListener:function(a,b){var c;if(!M.hasOwnProperty(a))return!1;for(c=M[a].length;0<=c;c-=1)M[a][c]===b&&M[a].splice(c,1);return!0},get scrollHeight(){return z.y},set scrollHeight(a){throw new SyntaxError("scrollHeight is currently read-only - ignoring "+
a);},get scrollLeft(){return-s.x},set scrollLeft(a){w(a,!1,!1);return-s.x},get scrollTop(){return-s.y},set scrollTop(a){w(!1,a,!1);return-s.y},get scrollWidth(){return z.x},set scrollWidth(a){throw new SyntaxError("scrollWidth is currently read-only - ignoring "+a);},get segmentCount(){return!k.snapping?{x:NaN,y:NaN}:{x:Math.ceil(z.x/r.x),y:Math.ceil(z.y/r.y)}},set segmentCount(a){throw new SyntaxError("segmentCount is currently read-only - ignoring "+a);},get currentSegment(){return{x:Ga,y:Ha}},
set currentSegment(a){throw new SyntaxError("currentSegment is currently read-only - ignoring "+a);},get contentContainerNode(){return A},set contentContainerNode(a){throw new SyntaxError("contentContainerNode is currently read-only - ignoring "+a);}}};FTScroller.prototype.getPrependedHTML=function(a,b,c){c||(c="object"===typeof FTScrollerOptions&&FTScrollerOptions.hwAccelerationClass?FTScrollerOptions.hwAccelerationClass:"ftscroller_hwaccelerated");var d='<div class="ftscroller_container">';a||(d+=
'<div class="ftscroller_x '+c+'">');b||(d+='<div class="ftscroller_y '+c+'">');return d};FTScroller.prototype.getAppendedHTML=function(a,b,c,d){c||(c="object"===typeof FTScrollerOptions&&FTScrollerOptions.hwAccelerationClass?FTScrollerOptions.hwAccelerationClass:"ftscroller_hwaccelerated");var e="";a||(e+="</div>");b||(e+="</div>");d&&(a||(e+='<div class="ftscroller_scrollbar ftscroller_scrollbarx '+c+'"><div class="ftscroller_scrollbarinner"></div></div>'),b||(e+='<div class="ftscroller_scrollbar ftscroller_scrollbary '+
c+'"><div class="ftscroller_scrollbarinner"></div></div>'));return e+"</div>"}})();
(function(){function b(b,c){throw new RangeError('"'+b+'" must be a number between 0 and 1. Got '+c+" instead.");}CubicBezier=function(d,c,g,l){0<=d&&1>=d||b("p1x",d);0<=c&&1>=c||b("p1y",c);0<=g&&1>=g||b("p2x",g);0<=l&&1>=l||b("p2y",l);this._p1={x:d,y:c};this._p2={x:g,y:l}};CubicBezier.prototype._getCoordinateForT=function(b,c,g){var l=3*c;c=3*(g-c)-l;return(((1-l-c)*b+c)*b+l)*b};CubicBezier.prototype._getCoordinateDerivateForT=function(b,c,g){var l=3*c;c=3*(g-c)-l;return(3*(1-l-c)*b+2*c)*b+l};CubicBezier.prototype._getTForCoordinate=
function(b,c,g,l){if(!isFinite(l)||0>=l)throw new RangeError('"epsilon" must be a number greater than 0.');var m,h,f,a;m=b;for(h=0;8>h;h+=1){f=this._getCoordinateForT(m,c,g)-b;if(Math.abs(f)<l)return m;a=this._getCoordinateDerivateForT(m,c,g);if(1E-6>Math.abs(a))break;m-=f/a}m=b;h=0;a=1;if(m<h)return h;if(m>a)return a;for(;h<a;){f=this._getCoordinateForT(m,c,g);if(Math.abs(f-b)<l)break;b>f?h=m:a=m;m=0.5*(a-h)+h}return m};CubicBezier.prototype.getPointForT=function(d){if(0===d||1===d)return{x:d,y:d};
(0>d||1<d)&&b("t",d);return{x:this._getCoordinateForT(d,this._p1.x,this._p2.x),y:this._getCoordinateForT(d,this._p1.y,this._p2.y)}};CubicBezier.prototype.getTForX=function(b,c){return this._getTForCoordinate(b,this._p1.x,this._p2.x,c)};CubicBezier.prototype.getTForY=function(b,c){return this._getTForCoordinate(b,this._p1.y,this._p2.y,c)};CubicBezier.prototype._getAuxPoints=function(d){(0>=d||1<=d)&&b("t",d);var c={x:d*this._p1.x,y:d*this._p1.y},g={x:this._p1.x+d*(this._p2.x-this._p1.x),y:this._p1.y+
d*(this._p2.y-this._p1.y)},l={x:this._p2.x+d*(1-this._p2.x),y:this._p2.y+d*(1-this._p2.y)},m={x:c.x+d*(g.x-c.x),y:c.y+d*(g.y-c.y)},h={x:g.x+d*(l.x-g.x),y:g.y+d*(l.y-g.y)};return{i0:c,i1:g,i2:l,j0:m,j1:h,k:{x:m.x+d*(h.x-m.x),y:m.y+d*(h.y-m.y)}}};CubicBezier.prototype.divideAtT=function(d){var c,g,l,m,h,f,a;(0>d||1<d)&&b("t",d);if(0===d||1===d)return f=[],f[d]=CubicBezier.linear(),f[1-d]=this.clone(),f;f=this._getAuxPoints(d);m=f.i0;d=f.i2;g=f.j0;l=f.j1;f=f.k;c=f.x;var e=f.y;f=m.x/c;a=m.y/e;m=g.x/c;
h=g.y/e;g=(l.x-c)/(1-c);l=(l.y-e)/(1-e);c=(d.x-c)/(1-c);d=(d.y-e)/(1-e);return[new CubicBezier(f,a,m,h),new CubicBezier(g,l,c,d)]};CubicBezier.prototype.divideAtX=function(d,c){(0>d||1<d)&&b("x",d);var g=this.getTForX(d,c);return this.divideAtT(g)};CubicBezier.prototype.divideAtY=function(d,c){(0>d||1<d)&&b("y",d);var g=this.getTForY(d,c);return this.divideAtT(g)};CubicBezier.prototype.clone=function(){return new CubicBezier(this._p1.x,this._p1.y,this._p2.x,this._p2.y)};CubicBezier.prototype.toString=
function(){return"cubic-bezier("+[this._p1.x,this._p1.y,this._p2.x,this._p2.y].join(", ")+")"};CubicBezier.linear=function(){return new CubicBezier};CubicBezier.ease=function(){return new CubicBezier(0.25,0.1,0.25,1)};CubicBezier.linear=function(){return new CubicBezier(0,0,1,1)};CubicBezier.easeIn=function(){return new CubicBezier(0.42,0,1,1)};CubicBezier.easeOut=function(){return new CubicBezier(0,0,0.58,1)};CubicBezier.easeInOut=function(){return new CubicBezier(0.42,0,0.58,1)}})();var module;
void 0!==module&&module.exports&&(module.exports=function(b,d){return new FTScroller(b,d)},module.exports.FTScroller=FTScroller,module.exports.CubicBezier=CubicBezier);
